Autores: Gabriel Costa de Moraes
e Pedro Miotto Mujica

# **Atividade avaliativa - Matrizes em Python**

Implementar os problemas de matrizes utilizando linguagem de programação Python e a biblioteca Numpy
- **Observação**: Sempre que um comando resultar em erro, explique o motivo com base na
teoria de matrizes. Para isso, insira comentários com sua explicação diretamente no
código.

Os códigos devem ser enviados no formato .txt ou:
- caso utilize o Jupyter Notebook, enviar o arquivo .ipynb;
- caso utilize o Google Colab, compartilhar o link (Recomendado).




### Considere as matrizes e resolva as situações propostas

$$
A=
\left(\begin{array}{cc}
3 & -2 & 5 & 1 & 6\\
-6 & 4 & -4 & 1 & 3\\
9 & -6 & 2 & 1 & 2\\
6 & -4 & -6 & 5 & 1\\
9 & 4 & 1 & 5 & 3\\
\end{array}\right)
B=
\left(\begin{array}{cc}
1 & 2 & 2 & 2 & 2\\
3 & 1 & 2 & 2 & 2\\
3 & 3 & 1 & 2 & 2\\
3 & 3 & 3 & 1 & 2\\
6 & 6 & 6 & 2 & 1\\
\end{array}\right)
C=
\left(\begin{array}{cc}
2 & -1 & 4\\
3 & 2 & 1\\
5 & 5 & 1\\
1 & 0 & 0\\
2 & 2 & 0\\
\end{array}\right)
$$

In [ ]:
#Importando bibliotecas
import numpy as np #Biblioteca para matrizes e cálculos
from sympy import * #Biblioteca para escrever equações

In [ ]:
#Declarando matrizes
a = np.matrix('3 -2 5 1 6; -6 4 -4 1 3; 9 -6 2 1 2; 6 -4 -6 5 1; 9 4 1 5 3')
b = np.matrix('1 2 2 2 2; 3 1 2 2 2; 3 3 1 2 2;  3 3 3 1 2; 6 6 6 2 1')
c = np.matrix('2 -1 4; 3 2 1; 5 5 1; 1 0 0; 2 2 0')
#Imprimindo Matrizes
a,b,c

(matrix([[ 3, -2,  5,  1,  6],
         [-6,  4, -4,  1,  3],
         [ 9, -6,  2,  1,  2],
         [ 6, -4, -6,  5,  1],
         [ 9,  4,  1,  5,  3]]),
 matrix([[1, 2, 2, 2, 2],
         [3, 1, 2, 2, 2],
         [3, 3, 1, 2, 2],
         [3, 3, 3, 1, 2],
         [6, 6, 6, 2, 1]]),
 matrix([[ 2, -1,  4],
         [ 3,  2,  1],
         [ 5,  5,  1],
         [ 1,  0,  0],
         [ 2,  2,  0]]))

**a) Exibir dimensões das matrizes**

In [ ]:
#Imprimindo as dimensões
#Output: Linha x Coluna
print(f"Dimensão da matriz A: {a.shape}")
print(f"Dimensão da matriz B: {b.shape}")
print(f"Dimensão da matriz C: {c.shape}")

Dimensão da matriz A: (5, 5)
Dimensão da matriz B: (5, 5)
Dimensão da matriz C: (5, 3)


**b) Exiba o elemento 𝑎<sub>33</sub> (elemento da terceira linha e terceira coluna da matriz 𝐴) e 𝑏<sub>53</sub>
(elemento da quinta linha e terceira coluna da matriz 𝐵**

In [ ]:
#A contagem dos elemntos de uma lista inicia em 0
#Logo será necessário mostrar a matriz na linha (3-1) e coluna (3-1)
print(f"Elemento de A33: {a[2,2]}")
print(f"Elemento de B53: {b[4,2]}")

Elemento de A33: 2
Elemento de B53: 6


**c) Exibir os elementos da quinta linha de 𝐴**

In [ ]:
print(f"Elementos da quinta linha da matriz A: \n")
Matrix(a[4])

Elementos da quinta linha da matriz A: 



Matrix([[9, 4, 1, 5, 3]])

**d) Exibir os elementos da terceira coluna de 𝐴;**

In [ ]:
print(f"Elementos da terceira coluna da matriz A: \n")
#Usar : para indicar que será imprimido a coluna
Matrix(a[:, 2])

Elementos da terceira coluna da matriz A: 



Matrix([
[ 5],
[-4],
[ 2],
[-6],
[ 1]])

**e) Exibir o resultado da multiplicação da segunda coluna de 𝐴 com a quarta linha de 𝐵;**

In [ ]:
#Armazena linhas e colunas nas variáveis
colunaA = np.array([-2, 4, -6, -4, 4])
linhaB = np.array([3, 3, 3, 1, 2])

#Armazenar o resultado com metódo .dot() que retorna o produto
produtoE = np.dot(colunaA,linhaB)

#Imprimir o resultado na tela
print(f"Multiplicação entre linha e coluna resulta em: {produtoE}")

Multiplicação entre linha e coluna resulta em: -8


**f) Exibir a matriz transposta de 𝐶 e sua respectiva dimensão**

In [ ]:
#Usar metódo Numpy para mostrar matriz transposta

matriz_transposta = c.transpose()
print(f"Dimensão da matriz: {np.shape(matriz_transposta)}")
print('\n')
Matrix(matriz_transposta)

Dimensão da matriz: (3, 5)




Matrix([
[ 2, 3, 5, 1, 2],
[-1, 2, 5, 0, 2],
[ 4, 1, 1, 0, 0]])

**g) exibir o resultado de 𝐴 + 𝐵, 𝐴 − 𝐵 e 𝐶 + 𝐴**

In [ ]:
#Primeira operação
op1 = a + b
print(f"Soma da A+B \n")
Matrix(op1)

Soma da A+B 



Matrix([
[ 4,  0,  7, 3, 8],
[-3,  5, -2, 3, 5],
[12, -3,  3, 3, 4],
[ 9, -1, -3, 6, 3],
[15, 10,  7, 7, 4]])

In [ ]:
#Segundo operação
op2 = a - b
print(f"Subtração da A-B \n")
Matrix(op2)

Subtração da A-B 



Matrix([
[ 2, -4,  3, -1,  4],
[-9,  3, -6, -1,  1],
[ 6, -9,  1, -1,  0],
[ 3, -7, -9,  4, -1],
[ 3, -2, -5,  3,  2]])

In [ ]:
#Terceira operação
op3 = c+a
Matrix(op3)
#Explicação do erro
#A matriz não pode ser calculada devido as diferentes dimensões
#Como A tem dimensão 5X3 e C tem dimensão 5X5 o cálculo não é possível

ValueError: operands could not be broadcast together with shapes (5,3) (5,5) 

**h) exibir o resultado de 𝐴 × 𝐵 e 𝐵 × 𝐴**

In [ ]:
produtoAB = np.dot(a,b)
print("Multiplicação entre A e B \n")
Matrix(produtoAB)

Multiplicação entre A e B 



Matrix([
[51, 58, 46, 25, 20],
[15,  1, 13, -5, -7],
[12, 33, 23, 15, 14],
[-3, 11, 19, -1,  3],
[57, 58, 60, 39, 41]])

In [ ]:
#Cálculo da matriz
produtoBA = np.dot(b,a)
print("Multiplicação entre B e A \n")

Matrix(produtoBA)
#Multiplicação de matrizes não é comutativa
#Logo A * B != B* A

Multiplicação entre B e A 



Matrix([
[39,  -6, -9, 25, 24],
[51, -14,  5, 26, 33],
[30,   0, -5, 27, 37],
[42,  -8,  5, 24, 40],
[57, -28,  7, 33, 71]])

**i) Exibir o resultado de 𝐴 × 𝐶 e 𝐶 × 𝐴**

In [ ]:
#Condição para multiplicação de matrizes
#Número de colunas da primeira matriz é igual ao número de linhas da segunda matriz
#Colunas de A = 5
#Linhass de C = 5

#Cálculo da Matriz
produtoAC = np.dot(a,c)

print("Multiplicação entre A e C \n")

Matrix(produtoAC)

Multiplicação entre A e C 



Matrix([
[ 38,  30,  15],
[-13,   0, -24],
[ 15,  -7,  32],
[-23, -42,  14],
[ 46,  10,  41]])

In [ ]:
#Cálculo da Matriz
produtoAC = np.dot(c,a)
print("Multiplicação entre c e a \n")
Matrix(produtoAC)

#Explicação do erro: Para obtenção do produto número de colunas da primeira matriz é igual ao número de linhas da segunda matriz
#Colunas de C = 3
#Linhas de C = 5
#Como 5 != 3 o produto entre as matrizes não pode ser calculado

ValueError: shapes (5,3) and (5,5) not aligned: 3 (dim 1) != 5 (dim 0)

**j) Exibir o que foi calculado no item (e) a partir do resultado da matriz 𝐵 × 𝐴 calculada
no item (h)**

In [ ]:
#Valor calculado no item e) aparece na matriz resultante de B X a

print(f"Resultado Item e) = {produtoE}")
print("\n")
print(f"Multiplicação entre B e A\n {produtoBA} ")
print("\n")
#Logo o valor calculado no item e) aparece na seguinte posição
print(f"O Valor calculado está presente na linha 4, coluna 2: {produtoBA[3,1]}")


Resultado Item e) = -8


Multiplicação entre B e A
 [[ 39  -6  -9  25  24]
 [ 51 -14   5  26  33]
 [ 30   0  -5  27  37]
 [ 42  -8   5  24  40]
 [ 57 -28   7  33  71]] 


O Valor calculado está presente na linha 4, coluna 2: -8


**k) Exibir os determinantes de 𝐴 e de 𝐵**

In [ ]:
#Metódo para calcular determinante
detA = np.linalg.det(a)
detB = np.linalg.det(b)

print(f"Determinante da matriz A: {detA}")
print(f"Determinante da matriz B: {detB}")

Determinante da matriz A: 9180.000000000004
Determinante da matriz B: 87.0


**l) Calcule as matrizes inversas de 𝐴, 𝐵 e 𝐶**

In [ ]:
#Metódo Numpy para calcular a inversa da Matriz A
invA = np.linalg.inv(a)
print("Matrix inversa de A: \n")
Matrix(invA)

Matrix inversa de A: 



Matrix([
[  -0.148583877995643,  0.108061002178649,  0.236601307189543,  -0.105882352941177, 0.0666666666666667],
[  -0.108496732026144,  0.101633986928105, 0.0803921568627451,  -0.114705882352941,                0.1],
[   0.189542483660131, -0.228758169934641, -0.254901960784314,  0.0588235294117647,                0.0],
[   0.320261437908497, -0.369281045751634, -0.568627450980392,   0.323529411764706,                0.0],
[-0.00653594771241829,   0.23202614379085,  0.215686274509804, -0.0882352941176471,                0.0]])

In [ ]:
invB = np.linalg.inv(b)
print("Matrix inversa de B: \n")
Matrix(invB)

Matrix inversa de B: 



Matrix([
[-0.448275862068966,  0.275862068965517,  0.137931034482759, 0.0229885057471266, 0.0229885057471264],
[ 0.103448275862069, -0.448275862068966,  0.275862068965517, 0.0459770114942528, 0.0459770114942529],
[ 0.206896551724138,  0.103448275862069, -0.448275862068966, 0.0919540229885057, 0.0919540229885058],
[ 0.413793103448276,  0.206896551724138,  0.103448275862069, -0.816091954022989,  0.183908045977012],
[               0.0,                0.0,                0.0,  0.666666666666667, -0.333333333333333]])

In [ ]:
#Para calcular a inversa da matriz a matriz deve ser quadrada
#A Matriz C não é quadrada pois tem dimensões 5X3
#Assim a inversa não pode ser calculada

#Metódo Numpy para calcular inversa
invC = np.linalg.inv(c)
print("Matrix inversa de C: \n")
Matrix(invC)


LinAlgError: Last 2 dimensions of the array must be square

Vamos tentar resolver, os seguintes sistemas de equações lineares:

Sistema A\begin{cases}
3x_1 - 2x_2 + 5x_3 + x_4 + 6x_5 = 48 \\
-6x_1 + 4x_2 - 4x_3 + x_4 + 3x_5 = 9 \\
9x_1 - 6x_2 + 2x_3 + x_4 + 2x_5 = 17 \\
6x_1 - 4x_2 - 6x_3 + 5x_4 + x_3 = 5 \\
9x_1 + 4x_2 + x_3 + 5x_4 + 3x_5 = 55
\end{cases}


Sistema B\begin{cases}
x_1 + 2x_2 + 2x_3 + 2x_4 + 2x_5 = 1 \\
3x_1 + x_2 + 2x_3 + 2x_4 + 2x_5 = 2 \\
3x_1 + 3x_2 + 3x_3 + 2x_4 + 2x_5 = 3 \\
3x_1 + 3x_2 + 3x_3 + 4x_4 + 2x_5 = 4 \\
6x_1 + 6x_2 + 6x_3 + 2x_4 + 4x_5 = 5
\end{cases}

Note que um sistema de equações lineares pode ser dado matricialmente como 𝐴𝑥 = 𝑏,
em que 𝐴 é uma matriz quadrada 𝑛 × 𝑛 (matriz dos coeficientes), enquanto 𝑥 e 𝑏 são
matrizes coluna 𝑛 × 1. Com base nessa informação, tente resolver os sistemas

In [ ]:
#Sistema (a)
sistemaA = Matrix([
    [3, -2, 5, 1, 6],
    [-6, 4, -4, 1, 3],
    [9, -6, 2, 1, 2],
    [6, -4, -6, 5, 1],
    [9, 4, 1, 5, 3]
])

valoresA = Matrix([48, 9, 17, 5, 55])

# Resolvendo os sistemas
solucao_a = sistemaA.LUsolve(valoresA)

solucao_a
# resultado estilo:
# x1
# x2
# x3
# x4
# x5

Matrix([
[1],
[2],
[3],
[4],
[5]])

In [ ]:
#Sistema (b)
A2 = Matrix([
    [1, 2, 2, 2, 2],
    [3, 1, 2, 2, 2],
    [3, 3, 1, 2, 2],
    [3, 3, 3, 1, 2],
    [6, 6, 6, 2, 4]
])

b2 = Matrix([1, 2, 3, 4, 5])

#Resolvendo os sistemas
#Erro NonInvertibleMatrixError
solucao_b = A2.LUsolve(b2)

solucao_b

NonInvertibleMatrixError: Matrix det == 0; not invertible.

Explicação do erro:

```
NonInvertibleMatrixError
```
O erro acima ocorre porque a matriz dos coeficientes de do sistemas tem determinante zero, o que significa que a matriz é singular. Isso indica que o sistema de equações pode não ter uma solução única, ou pode ser que o sistema tenha infinitas soluções.
